### ISSUE TITLE
Chaincode with commented functions = faults

### ISSUE THREAD

**Issue by ruslan120101** [IBM-Blockchain/ibm-blockchain-js#12]
Leaving functions intact but commented in Chaincode results in false positives 

As of https://github.com/ruslan120101/marbles-chaincode/commit/830007b1270e7991fdc467342c7cd04276a0a96a, 

```
[ibc-js] Scanning files [ 'part2_works_with_sdk_v1.0.0.go' ]
[ibc-js] Parsing file for invoke functions - part2_works_with_sdk_v1.0.0.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - part2_works_with_sdk_v1.0.0.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
```

Removing commented functions works as expected
https://github.com/ruslan120101/marbles-chaincode/commit/cd9a0a44e986f215edc654d03087522c928b1882

(no invoke functions found, as expected)
```
[ibc-js] Parsing file for query functions - part2_works_with_sdk_v1.0.0.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
```

Looks like a parsing issue

**Comment by dshuffma-ibm** [comment]
The logic in the parsing go functions is simplistic at best.  Its a regular expression searching for function calls using the `function` parameter inside the Invoke/Run and Query parent function. It should work for non-tricky setups, but there are more false positives then what you have outlined.  At any rate, it won't be improved anytime soon because it works well _enough_ for 95% of cases.

I believe that actually identifying Go functions with 100% certainty would require integrating with a Go compiler.  This seems quite complicated in user env setup and just a compete pain for our scope. 

I am completely open to implementing/taking better way to parse the functions, but it should not require weird/advanced environmental setup. For the time being we should accept that false positives are acceptable.
