### ISSUE TITLE
no local chaincode deployment

### ISSUE THREAD

**Issue by blockchaindul** [IBM-Blockchain/ibm-blockchain-js#18]
I run takes marvels chaincode local download, it did not find the directory connection ...

Under inde part of the js code, I'd like to run the js chaincode local, download the code in relation to the local server time-consuming just to be running on the local server. 

How can I change non-zip and unzip and local chaincode call in the following?

            zip_url: 'https://github.com/ibm-blockchain/marbles-chaincode/archive/master.zip', 
            unzip_dir: 'marbles-chaincode-master / part2_v1.0.0', 
            git_url: 'https://github.com /ibm-blockchain/marbles-chaincode/part2_v1.0.0 '

**Comment by masterDev1985** [comment]
I'm afraid the only way to deploy chaincode using ibm-blockchain-js is by storing it on a public github repository.  This is because ibm-blockchain-js uses the REST API on each peer in the network in order to deploy, invoke, and query chaincode.  This interface does not allow for you to deploy your chaincode from a local folder.

My recommendation would be to investigate the new SDK that is coming from the Hyperledger fabric team. This SDK will support deploying chaincode from a local folder.  [Click here](https://github.com/hyperledger/fabric/tree/master/sdk/node#readme) to see the SDK.
