### ISSUE TITLE
filter_users function limits use of custom usernames in obcca

### ISSUE THREAD

**Issue by jellevdp** [IBM-Blockchain/ibm-blockchain-js#3]
The following filter is being applied inside the ibc.register() function in order to filter out the users that are of the 'client' usertype. However, this function seems to be specifically build for the standard demo in which the usernames as given in the Marbles demo - app.js file start with user_type1_ . 

`//==================================================================
//filter_users() - only get client level usernames - [1=client, 2=nvp, 4=vp, 8=auditor accurate as of 2/18]
//==================================================================
function filter_users(users){

	var valid_users = [];
	for(var i = 0; i < users.length; i++) {

		if(users[i].username.indexOf('user_type1') == 0){		//type should be 1 for client
			valid_users.push(users[i]);
		}
	}
	return valid_users;
}`

Suggestion would be to give the user object an additional attribute to store their user type which the SDK filter_users function can filter on.

**Comment by dshuffma-ibm** [comment]
Thanks for the suggestion, but I want to *try* to keep the options as clean and user friendly as possible.  I feel this is an unneeded change since you can still achieve what you want with the existing code (see my comment below). I would agree that I did not detail this action at all in my documentation, which I have corrected in https://github.com/IBM-Blockchain/ibm-blockchain-js/commit/165a4d59849e7f721c0dba32a2e048527b3704cd. 

I've added a [FAQ section](https://github.com/IBM-Blockchain/ibm-blockchain-js#faq) to the readme with this response:
Correct behavior of ibc.load() is to remove any usernames that do not contain 'type_1' in their name. This is to conform to the OBC Peer spec of what usernames a dev's app should use. If this is not applicable for your network (ie you have a custom IBM Blockchain network) you can easily create your own version of ibc.load() for your needs. I would copy the code found in ibc.load() then modifiy it to fit your own needs. Everything important that ibc.load() calls is exposed in this module.
